import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('language switch exposes a reusable children wrapper module', async () => {
    const [component, entry, readme, showcasePage, showcaseStyle] = await Promise.all([
        readFile('src/components/LanguageSwitch/LanguageSwitch.tsx', 'utf8'),
        readFile('src/components/LanguageSwitch/index.ts', 'utf8'),
        readFile('src/components/LanguageSwitch/README.md', 'utf8'),
        readFile('src/showcase/components/language-switch/LanguageSwitchShowcasePage.tsx', 'utf8'),
        readFile('src/showcase/components/language-switch/LanguageSwitchShowcasePage.scss', 'utf8'),
    ])

    assert.match(component, /children\?:\s*ReactNode/)
    assert.match(component, /languageIconUrl from '@\/assets\/layout\/headbar\/lang\.svg'/)
    assert.doesNotMatch(component, /import \{ Icon \} from '@\/components\/Icon'/)
    assert.match(component, /APP_CONFIG\.enableI18n/)
    assert.match(component, /style=\{\{ display: 'none' \}\}/)
    assert.match(component, /function LanguageSwitchContent/)
    assert.match(component, /useState\(false\)/)
    assert.match(component, /import \{ Picker/)
    assert.match(component, /APP_LANGUAGES/)
    assert.match(component, /changeAppLanguage/)
    assert.match(component, /useAppStore/)
    assert.match(component, /useTranslation/)
    assert.match(component, /useRef/)
    assert.match(component, /onClick=\{handleOpenLanguageSwitch\}/)
    assert.match(component, /setShowLanguagePopup\(true\)/)
    assert.match(component, /setShowLanguagePopup\(false\)/)
    assert.match(component, /<Picker\s+show=\{showLanguagePopup\}/)
    assert.match(component, /options=\{languagePickerOptions\}/)
    assert.match(component, /value=\{pendingLanguageIndex\}/)
    assert.match(component, /onChange=\{handleLanguagePickerChange\}/)
    assert.match(component, /onConfirm=\{handleLanguagePickerConfirm\}/)
    assert.match(component, /onAfterClose=\{handleLanguagePopupAfterClose\}/)
    assert.match(component, /confirmedLanguageCodeRef\.current = option\.value/)
    assert.match(component, /closeLanguageSwitch\(\)/)
    assert.match(component, /async function handleLanguagePopupAfterClose/)
    assert.match(component, /const languageCodeToChange = confirmedLanguageCodeRef\.current/)
    assert.match(component, /const hasLanguageChanged = option\.value !== languageCode/)
    assert.match(component, /if \(!hasLanguageChanged\) return/)
    assert.match(component, /window\.location\.reload\(\)/)
    assert.match(component, /const triggerContent = children === undefined \?/)
    assert.match(component, /language-switch__default/)
    assert.match(component, /<img src=\{languageIconUrl\}/)
    assert.doesNotMatch(component, /<Icon name="arrow-down"/)
    assert.match(component, /\{triggerContent\}/)
    assert.match(entry, /export \{ LanguageSwitch \} from '\.\/LanguageSwitch\.tsx'/)
    assert.match(readme, /children/)
    assert.doesNotMatch(readme, /Vue|slot/)
    assert.match(readme, /Default icon trigger/)
    assert.match(readme, /Custom button trigger/)
    assert.match(readme, /Picker/)
    assert.match(readme, /reloads the page/)
    assert.match(showcasePage, /export function LanguageSwitchShowcasePage/)
    assert.match(showcasePage, /useAppStore/)
    assert.match(showcasePage, /<SecondaryHeader title="语言切换" \/>/)
    assert.doesNotMatch(showcasePage, /Vue|slot/)
    assert.doesNotMatch(showcasePage, /useState/)
    assert.doesNotMatch(showcasePage, /打开次数/)
    assert.doesNotMatch(showcasePage, /onOpen/)
    assert.match(showcasePage, /<LanguageSwitch \/>/)
    assert.match(showcasePage, /<LanguageSwitch>/)
    assert.match(showcasePage, /默认图标入口/)
    assert.match(showcasePage, /自定义按钮入口/)
    assert.match(showcasePage, /切换语言/)
    assert.match(showcasePage, /className="full-btn mt-30"/)
    assert.match(showcasePage, /className="flex items-center mt-30"/)
    assert.doesNotMatch(showcaseStyle, /&-icon-row/)
    assert.doesNotMatch(showcaseStyle, /&-trigger/)
    assert.match(showcaseStyle, /\.language-switch-showcase\s*\{/)
})
